### ISSUE TITLE
Lack of subset capability -- always need to get entire obj

### ISSUE THREAD

**Issue by MrCreosote** [kbase/nextgen#10]
https://github.com/kbase/nextgen/blame/master/docs/challenges/data.md#L27

This is incorrect - all three data stores have extensive subsetting capabilities.

**Comment by dangunter** [comment]
I was told we need to get the whole genome. I realize that Mongo and I assume others can choose properties. So I think this is a property of the way the methods work (maybe also the way Shock works). Anyways, the more important point is that we need subsets.

**Comment by MrCreosote** [comment]
I don't know what the context here is, but the workspace allows you to pick parts of the genome object by path. The drawback is that the entire object has to be pulled from shock for the workspace to process it (which can be a lot faster than pulling the entire object to a webpage, but not necessarily). It'd definitely be better if the subsetting happened in place.

**Comment by dangunter** [comment]
ok, sounds good. I'll close this one on that note.
