### ISSUE TITLE
What does "data copies may not be complete" mean?

### ISSUE THREAD

**Issue by jaredbischof** [kbase/nextgen#27]
https://github.com/kbase/nextgen/blame/master/docs/challenges/data.md#L12

I would like to know exactly what this refers to.  If it refers to the fact that sometimes references to data are used instead of the actual data, that doesn't seem like a weakness.  Often times applications use references to large data objects rather than creating a copy of the entire object to improve performance and save space.  The fact that it's not a complete copy should be transparent to the user.  But, perhaps that's not what this is referring to.

**Comment by dangunter** [comment]
Thanks for the feedback, Jared. Can you open this as an issue in the nextgen repo in JIRA and assign it to Matt?

**Comment by dangunter** [comment]
I have moved this issue to JIRA (and assigned to Matt, for now)

https://atlassian.kbase.us/browse/NEXTGEN-12
