### ISSUE TITLE
One way references?

### ISSUE THREAD

**Issue by MrCreosote** [kbase/nextgen#8]
https://github.com/kbase/nextgen/blame/master/docs/challenges/data.md#L11

>all refs hierarchical/one-way

I'm not sure I understand this - references in the workspace are one way because they're created at the time of object creation, and obviously you can't create a reference to an object that doesn't exist. Beyond that, the reference graph is a DAG (not a tree as implied above) with this method which has many nice properties. Finally, in the current implementation although the references have a direction, you can follow references in either direction.

**Comment by dangunter** [comment]
So: can references be added to an object later? If so, is it still possible to navigate from referree to referrer

**Comment by MrCreosote** [comment]
No, data objects cannot reference other objects that did not exist when the former object was created, because objects are immutable. You can, of course, make a new version of the object with the added reference.

**Comment by dangunter** [comment]
I have moved this to JIRA (and assigned to Matt, for now)

https://atlassian.kbase.us/browse/NEXTGEN-11
